import React, { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Terminal, Send, X, Sparkles } from 'lucide-react';
import { saveWorkflowState, clearWorkflowState } from '../../lib/workflow';

export const Copilot: React.FC = () => {
  const navigate = useNavigate();
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const [input, setInput] = useState<string>('');
  const [history, setHistory] = useState<{ type: 'cmd' | 'resp'; text: string }[]>([
    { type: 'resp', text: 'VYUH Tactical Copilot v2.0 initialized. Type /help for available commands.' }
  ]);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [history]);

  const handleCommand = (cmdStr: string) => {
    const raw = cmdStr.trim();
    if (!raw) return;

    setHistory(prev => [...prev, { type: 'cmd', text: raw }]);
    setInput('');

    const args = raw.split(' ');
    const command = args[0].toLowerCase();
    const param = args.slice(1).join(' ');

    switch (command) {
      case '/help':
        setHistory(prev => [...prev, {
          type: 'resp',
          text: 'Available Commands:\n/trace [id] - Route directly to Graph analytics\n/dispatch [area] - Locate coordinates & deploy patrol units\n/verify - Redirect to Currency verifier scanner\n/clear - Reset active investigation context\n/bns - Print BNS law citations relevant to cyber arrests'
        }]);
        break;
      case '/trace':
        if (!param) {
          setHistory(prev => [...prev, { type: 'resp', text: 'Error: Provide an Account ID or phone to trace. e.g., /trace 9876543201' }]);
        } else {
          saveWorkflowState({
            activeStep: 'graph_intelligence',
            data: {
              caseId: `VYUH-2026-COP-${Math.floor(1000 + Math.random() * 9000)}`,
              accountId: param,
              phone: param.startsWith('+91') ? param : '+919876500001',
              ringId: 7
            }
          });
          setHistory(prev => [...prev, { type: 'resp', text: `Tracing account ${param}. Loading homology node clusters...` }]);
          setTimeout(() => {
            navigate('/fraud-graph');
            setIsOpen(false);
          }, 800);
        }
        break;
      case '/dispatch':
        if (!param) {
          setHistory(prev => [...prev, { type: 'resp', text: 'Error: Provide target district/sector. e.g., /dispatch New Delhi' }]);
        } else {
          saveWorkflowState({
            activeStep: 'crime_map',
            data: {
              caseId: `VYUH-2026-COP-${Math.floor(1000 + Math.random() * 9000)}`,
              state: 'Delhi',
              district: param,
              accountId: '9876543201',
              ringId: 7
            }
          });
          setHistory(prev => [...prev, { type: 'resp', text: `Locating coordinates for ${param}. Requesting patrol recommendations...` }]);
          setTimeout(() => {
            navigate('/map');
            setIsOpen(false);
          }, 800);
        }
        break;
      case '/verify':
        setHistory(prev => [...prev, { type: 'resp', text: 'Redirecting to banknote verifier...' }]);
        setTimeout(() => {
          navigate('/currency');
          setIsOpen(false);
        }, 500);
        break;
      case '/clear':
        clearWorkflowState();
        setHistory(prev => [...prev, { type: 'resp', text: 'Context cleared. Pipeline reset.' }]);
        break;
      case '/bns':
        setHistory(prev => [...prev, {
          type: 'resp',
          text: 'IPC/BNS Citations:\n- Sec 318 BNS: Punishment for cheating/mule fronts.\n- Sec 66D IT Act: Cheating by personation using computer resource.'
        }]);
        break;
      default:
        // Mock simple AI RAG response if not a slash command
        const low = raw.toLowerCase();
        let reply = '';
        if (low.includes('65b') || low.includes('evidence')) {
          reply = 'Agent: Section 65B of the Indian Evidence Act requires a signed certificate asserting that the electronic document was generated by a computer in regular use. VYUH automates this with digital MD5/SHA-256 seal signatures in the Evidence Locker.';
        } else if (low.includes('louvain') || low.includes('ring') || low.includes('community')) {
          reply = 'Agent: The Louvain community algorithm optimizes network modularity. It maximizes internal transaction weight inside groups relative to external ones, isolating coordinated mule networks.';
        } else if (low.includes('hotspot') || low.includes('mewat') || low.includes('jamtara')) {
          reply = 'Agent: Threat radar coordinates show Mewat dominates in digital arrest scam vectors, while Jamtara has high UPI cashout velocity indicators.';
        } else {
          reply = `Agent: Mapped query "${raw}". Run "/trace" to query graph networks, "/dispatch" to deploy local cyber cells, or "/bns" for legal code citations.`;
        }
        setHistory(prev => [...prev, { type: 'resp', text: reply }]);
        break;
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-45 no-print">
      {isOpen ? (
        <div className="w-85 bg-bg-surface border border-accent-blue/35 rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-fade-in backdrop-blur-md">
          {/* Header */}
          <div className="px-4 py-3 bg-bg-primary/50 border-b border-border-custom flex justify-between items-center select-none">
            <div className="flex items-center space-x-2 text-accent-blue font-mono font-bold text-xs">
              <Terminal className="w-4 h-4 animate-pulse" />
              <span>VYUH COPILOT Terminal</span>
            </div>
            <button 
              onClick={() => setIsOpen(false)}
              className="text-text-secondary hover:text-text-primary transition"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Chat/Command logs */}
          <div className="flex-1 h-60 overflow-y-auto p-4 space-y-3 font-mono text-[10px] text-green-400 bg-black/60 leading-relaxed scrollbar-thin">
            {history.map((h, i) => (
              <div key={i} className={h.type === 'cmd' ? 'text-text-primary' : 'text-green-400 whitespace-pre-wrap'}>
                {h.type === 'cmd' ? `> ${h.text}` : h.text}
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          {/* Form input */}
          <div className="p-2.5 border-t border-border-custom flex items-center gap-2 bg-bg-primary/30">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') handleCommand(input);
              }}
              placeholder="Type command e.g., /help, /trace..."
              className="flex-1 bg-[#060a16] border border-border-custom rounded-lg px-3 py-1.5 font-mono text-[11px] text-text-primary placeholder-text-secondary focus:outline-none focus:border-accent-blue leading-relaxed"
            />
            <button
              onClick={() => handleCommand(input)}
              className="p-1.5 bg-accent-blue hover:bg-accent-blue-hover text-text-primary rounded-lg transition"
            >
              <Send className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      ) : (
        <button
          onClick={() => setIsOpen(true)}
          className="p-3 bg-accent-blue hover:bg-accent-blue-hover text-text-primary rounded-full shadow-lg shadow-accent-blue/25 hover:scale-105 transition flex items-center gap-1.5 font-mono font-bold text-xs select-none glow-accent cursor-pointer border border-accent-blue/40"
        >
          <Sparkles className="w-4.5 h-4.5 animate-spin-slow" />
          Copilot CLI
        </button>
      )}
    </div>
  );
};

export default Copilot;
